theme: jekyll-theme-cayman

title: The Foundations of New York
description: A Maximum New York class
color:
  header: "#000"
  gradient_left: "#e53935"
  gradient_right: "#f57c00"
logo_url: https://github.githubassets.com/images/icons/emoji/octocat.png
buttons:
  zip_url: https://github.com/tuur29/pages-themes-cayman
  zip_title: Visit MNY Site
  zip_hide: false
  tar_hide: true
  github_hide: true
